import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontFamily: 'Helvetica',
        backgroundColor: '#ffffff'
    },
    header: {
        fontSize: 24,
        marginBottom: 20,
        textAlign: 'center',
        fontWeight: 'bold',
        textTransform: 'uppercase',
        color: '#333'
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 0
    },
    row: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        paddingVertical: 8
    },
    label: {
        width: 120,
        fontWeight: 'bold',
        color: '#555',
        fontSize: 12
    },
    value: {
        flex: 1,
        fontSize: 12,
        color: '#000'
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        textAlign: 'center',
        fontSize: 10,
        color: 'grey'
    },
    verificationBadge: {
        marginVertical: 20,
        padding: 15,
        backgroundColor: '#f0fdf4',
        // color: '#166534', // React-PDF doesn't support color validation on View, use Text color
        textAlign: 'center',
        borderRadius: 5
    },
    badgeText: {
        color: '#166534',
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'bold'
    },
    subHeader: {
        fontSize: 16,
        marginBottom: 10,
        fontWeight: 'bold',
        color: '#333',
        borderBottomWidth: 2,
        borderBottomColor: '#333',
        paddingBottom: 5
    }
});

interface VehicleData {
    make: string;
    model: string;
    year: number;
    regNumber: string;
    vin?: string | null;
    expenses: { description: string; date: string }[];
}

export const CertificatePDF = ({ vehicle, companyName }: { vehicle: VehicleData, companyName: string }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <Text style={styles.header}>Verified by {companyName}</Text>

            <View style={styles.verificationBadge}>
                <Text style={styles.badgeText}>Officially Verified by {companyName}</Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.subHeader}>Vehicle Details</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Make:</Text>
                    <Text style={styles.value}>{vehicle.make}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Model:</Text>
                    <Text style={styles.value}>{vehicle.model}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Year:</Text>
                    <Text style={styles.value}>{vehicle.year}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Registration:</Text>
                    <Text style={styles.value}>{vehicle.regNumber}</Text>
                </View>
                {vehicle.vin && (
                    <View style={styles.row}>
                        <Text style={styles.label}>VIN:</Text>
                        <Text style={styles.value}>{vehicle.vin}</Text>
                    </View>
                )}
            </View>

            <View style={styles.section}>
                <Text style={styles.subHeader}>Verified Maintenance & Repairs</Text>
                {vehicle.expenses.length > 0 ? (
                    vehicle.expenses.map((exp, index) => (
                        <View key={index} style={styles.row}>
                            <Text style={{ flex: 1, fontSize: 10 }}>{exp.description}</Text>
                            <Text style={{ width: 100, textAlign: 'right', fontSize: 10 }}>{exp.date}</Text>
                        </View>
                    ))
                ) : (
                    <Text style={{ fontSize: 10, fontStyle: 'italic', color: '#666' }}>No public maintenance records available.</Text>
                )}
            </View>

            <Text style={styles.footer}>
                Generated by {companyName}. This document is a certification of the vehicle&apos;s history as recorded in our system.
                Verification Date: {new Date().toLocaleDateString()}
            </Text>
        </Page>
    </Document>
);

export default CertificatePDF;
